#!/bin/sh


USB_LOCATION=$(echo $DEVPATH | awk -F '/' '{print $6}')

# This is written separating reading and writing on purpose
echo $(cat /var/run/autokit/devices | jq "del(.devices[\"${USB_LOCATION}\"])") > /var/run/autokit/devices 