#!/bin/sh

AUTOKIT_ROOT=/dev/autokit

# This is written separating reading and writing on purpose
echo $(cat /var/run/autokit/devices | jq ".devices += {\"${1}\": { \"type\": \"${3}\", \"path\": \"${AUTOKIT_ROOT}/$1/$3\" }}") > /var/run/autokit/devices 